# Generated by Django 4.2.6 on 2023-10-23 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_alter_wallet_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
